### ISSUE TITLE
Day mode ne fonctionne pas

### ISSUE THREAD

**Issue by lhirlimann** [franck-paul/dayMode#4]
Bonjour, suite à la mise à jour de la 2.28.1 et de Daymode 5.1. Le widget ne fonctionne plus.

Dans ma conf j'ai : 
![image](https://github.com/franck-paul/dayMode/assets/415751/85a19d65-d086-4d08-bea9-7ebd40f1a28d)

Dans le rendu, le CSS est pété et j'ai l'erreur suivante:
![image](https://github.com/franck-paul/dayMode/assets/415751/eb5f6192-4789-4b8f-a759-537317308cba)

Auriez-vous besoin de logs, si oui lesquels ?

**Comment by Philippe-dev** [comment]
j'ai proposé une correction du plugin dans le fil du forum : https://forum.dotclear.org/viewtopic.php?pid=350843#p350843

**Comment by lhirlimann** [comment]
la correction, fonctionne chez moi
